services:
  postgres:
    image: postgres:14-alpine
    environment:
      POSTGRES_USER: vibeuser
      POSTGRES_PASSWORD: vibepassword
      POSTGRES_DB: vibechat
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U vibeuser -d vibechat"]
      interval: 5s
      timeout: 5s
      retries: 5

  backend:
    build:
      context: ./vibe-chat/backend
      dockerfile: Dockerfile.dev
    volumes:
      - ./vibe-chat/backend:/app
      - /app/node_modules
    ports:
      - "4000:4000"
    environment:
      NODE_ENV: development
      PORT: 4000
      DATABASE_URL: postgres://vibeuser:vibepassword@postgres:5432/vibechat
      JWT_SECRET: dev_jwt_secret_key_change_in_production
      AWS_S3_BUCKET: vibe-chat-local
      AWS_REGION: us-east-1
      CORS_ORIGIN: http://localhost:3000
      USE_MOCK_S3: "true"
    depends_on:
      postgres:
        condition: service_healthy
    command: >
      sh -c "
        echo 'Running database migrations...' &&
        npx prisma generate &&
        npx prisma migrate deploy &&
        echo 'Starting backend server...' &&
        npm run dev
      "

  frontend:
    build:
      context: ./vibe-chat/frontend
      dockerfile: Dockerfile.dev
    volumes:
      - ./vibe-chat/frontend:/app
      - /app/node_modules
    ports:
      - "3000:3000"
    environment:
      NODE_ENV: development
      REACT_APP_API_URL: http://localhost:4000
      REACT_APP_WS_URL: http://localhost:4000
    depends_on:
      - backend

volumes:
  postgres_data: 